version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - LeonErath
  assignees:
  - LeonErath
  ignore:
  - dependency-name: chart.js
    versions:
    - "> 1.1.1"
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.5
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
  - dependency-name: react-spinners
    versions:
    - 0.10.4
