version: "2"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  website:
    build:
      .
    ports:
      - "3000:3000"
    networks:
      - internal
      - proxy
