version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  website:
    image: leonerath/website:latest
    ports:
      - "3000:3000"
    restart: always
    labels:
      - traefik.backend=website
      - traefik.frontend.rule=Host:leonerath.de,www.leonerath.de,erath.dev,www.erath.dev
      - traefik.docker.network=proxy
      - traefik.port=3000
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - internal
      - proxy
  watchtower:
    image: v2tec/watchtower
    command: --interval 60 --label-enable --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
