version: "2"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  website:
    build:
      context: .
      args:
        - REACT_APP_GITHUB_PERSONAL_ACCESS_TOKEN=${REACT_APP_GITHUB_PERSONAL_ACCESS_TOKEN}
    ports:
      - "3000:3000"
    networks:
      - internal
      - proxy
