version: "2"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  watchtower:
    image:  v2tec/watchtower
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/spme/.docker/config.json:/config.json
    command: --interval 300 --label-enable
  website:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "3000:3000"
    restart: always
    labels:
      - traefik.backend=website
      - traefik.frontend.rule=Host:leonerath.de,www.leonerath.de
      - traefik.docker.network=proxy
      - traefik.port=3000
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - internal
      - proxy
