version: "2"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  website:
    build: leonerath/website:latest
    ports:
      - "3000:3000"
    restart: always
    labels:
      - traefik.backend=website
      - traefik.frontend.rule=Host:leonerath.de,www.leonerath.de,erath.dev,www.erath.dev
      - traefik.docker.network=proxy
      - traefik.port=3000
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - internal
      - proxy
  watchtower:
    image:  containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 300
