version: 2.0
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      # build the application image
      - run: docker build -f Dockerfile -t website .

      - run: docker run --name website -d -p 80:80 --rm website

      - run: docker exec -it website bash -c "yarn run build" 
  test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      
      - run: docker build -f Dockerfile -t website .

      - run: docker run --name website -d -p 80:80 --rm website
     
      - run: docker exec -it website bash -c "yarn test"
  deploy:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "33:c9:99:69:2b:8a:47:ee:d2:7f:87:17:a5:92:54:ce"

      - run: |
          docker build -f Dockerfile-prod -t leonerath/website .
          docker login -u $DOCKER_USER -p $DOCKER_PASS    
          docker push leonerath/website
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
