version: 2.0
jobs:
  deploy:
    machine:
      machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "33:c9:99:69:2b:8a:47:ee:d2:7f:87:17:a5:92:54:ce"
      - run: docker build -f Dockerfile -t leonerath/website . --build-arg REACT_APP_GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_TOKEN}
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push leonerath/website
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
