version: 1
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI

     # build the application image
     - run: docker build -f Dockerfile -t website .

     # deploy the image
     - run: docker run --name website -d -p 80:80 --rm website

     - run: docker exec -it website bash -c "npm run build"